name : Main Workflow
on: [push ,workflow_dispatch]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: get the code
        uses: actions/checkout@v3
      - name: setup node version 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: install node module
        run: npm ci
      - name: lint the app
        run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: get the code
        uses: actions/checkout@v3
      - name: setup node version 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: install node module
        run: npm ci
      - name: Build the app
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: get the code
        uses: actions/checkout@v3
      - name: setup node version 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: install node module
        run: npm ci
      - run: ls
      - name: Build the app
        run: npm run build
      - run : ls
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: dist
      - name: Infromation
        run: echo "Build completed"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Donwoload artifact
        uses: actions/download-artifact@v4
      - name: Show strcture
        run: ls
      - name: Deplyments
        run: echo "Deploying ..."



